### ISSUE TITLE
Configuration options to modify JanusGraph’s caching behavior on dynamodb

### ISSUE THREAD

**Issue by sinha-abhishek** [awslabs/dynamodb-janusgraph-storage-backend#203]
I see the dynamodb.properties file do not have options for modifying caching behaviour. How is the database caching supposed to work when using dynamodb as janusgraph backend?

**Comment by amcp** [comment]
Just because dynamodb.properties does not include samples of configuring caching behavior does not mean that caching is not supported. JanusGraph supports [caching at the transaction and database level](http://docs.janusgraph.org/latest/caching.html). You can find the [caching configuration options here](http://docs.janusgraph.org/latest/config-ref.html#_cache).
