### ISSUE TITLE
storage.dynamodb.client.endpoint not set in dynamodb.properties

### ISSUE THREAD

**Issue by jfstephe** [awslabs/dynamodb-janusgraph-storage-backend#237]
[dynamodb.properties](https://github.com/awslabs/dynamodb-janusgraph-storage-backend/blob/master/src/test/resources/dynamodb.properties) doesn't have an entry for storage.dynamodb.client.endpoint, unlike the local and docker flavours, and according to the [docs](https://github.com/awslabs/dynamodb-janusgraph-storage-backend/blob/master/README.md) (and from what I can see from the code) there isn't a default.

Is this an oversight or by design? Can a comment be added to the dynamodb.properties file to explain this please?

**Comment by amcp** [comment]
@jfstephe This is by design. Recent versions of the AWS SDK built into this project prefer specifying the endpoint using the region (eg, `us-west-1`) rather than by endpoint. Most services do not have local versions like DynamoDB Local. I can add a comment suggesting an override in case you want to test with DynamoDB Local using the storage.dynamodb.client.endpoint configuration, but [dynamodb-local.properties already does this](https://github.com/awslabs/dynamodb-janusgraph-storage-backend/blob/master/src/test/resources/dynamodb-local.properties#L30).

**Comment by jfstephe** [comment]
Aaahhh ok.... ....perhaps a comment explaining why there is no endpoint in the non-local properties file or in the java code along the lines of what you said above might help peeps. Not urgent obviously, but if you are in that area [:-).
Thanks for getting back to me.
