### ISSUE TITLE
Hashkey has exceeded the maximum size limit of2048 bytes

### ISSUE THREAD

**Issue by sglee18** [awslabs/dynamodb-janusgraph-storage-backend#296]
Hello,

We are migrating from Titan (HBase backend) to JanusGraph (Dynamodb backend). We exported all the vertices and edges and reimport them into JanusGraph.

We encountered the following error message when creating vertices via JanusGraph:

20:18:22.644 [getDelegate-8] DEBUG com.amazonaws.request - Received error response: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: One or more parameter values were invalid: Size of hashkey has exceeded the maximum size limit of2048 bytes (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 2V6NEF7K3OSBEA83D8K1QV0I2VVV4KQNSO5AEMVJF66Q9ASUAAJG)

We have opened a case ticket with AWS team - ID5423092821. 

Thanks,
Lee

**Comment by sglee18** [comment]
This is resolved.

**Comment by amcp** [comment]
This was probably due to an indexed property exceeding the maximum allowable size of the hash key (2048 bytes). Please limit the size of your indexed properties to less than 2048 bytes. Due to the encoding used and the data type you are indexing, you may need to use some trial and error to find the actual upper bound

**Comment by sglee18** [comment]
That is exactly what I did. I removed the indexed property that exceeded the limitation and resolved the problem. Thanks for your reply.
